services:
  - type: worker
    name: spiritual-empire
    env: python
    region: oregon
    plan: starter
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python empire_engine.py
